[package]
name = "rust_ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.*"
ansiterm = "0.12.2"
byte-unit = "4.0.19"
chrono = "0.4.30"
locale = "0.2"
